name: IOS Build Release

concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true

on:
    deployment

jobs:
    build:
        runs-on: macOS-11
        environment: production

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Get React Native Arsenal
              run: |
                  git clone https://gitlab.com/nepware-internals/react-native-arsenal.git src/vendor/react-native-arsenal

            - name: Cache Ruby gems
              uses: actions/cache@v3
              with:
                  path: ios/vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-

            - name: Cache Pods
              uses: actions/cache@v3
              with:
                path: |
                  ios/Pods
                  ~/Library/Caches/CocoaPods
                  ~/.cocoapods
                key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-pods-

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: '**/yarn.lock'

            - name: Install Dependencies
              run: |
                  yarn install --non-interactive

            - name: Install Pods
              run: cd ios && pod install --repo-update && cd ..

            - name: Run Fastlane
              uses: maierj/fastlane-action@v2.2.0
              with:
                  skip-tracking: true
                  lane: 'beta'
                  subdirectory: 'ios'
                  bundle-install-path: vendor/bundle
              env:
                  FASTLANE_HIDE_CHANGELOG: true
