name: Android Build Release

concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: true

on:
    pull_request:
    push:
        branches:
            - 'develop'
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.ref_type == 'tag' && 'production' || 'staging' }}

        steps:
            - name: Checkout Commit
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Export secrets
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Export vars
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(vars) }}

            - name: Decrypt secret files
              env:
                INPUT_FILES: ./android/release.keystore.gpg
              run: |
                  for encrypted_file in ${INPUT_FILES//,/ }
                  do
                    gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output "${encrypted_file%.*}" "$encrypted_file"
                  done

            - name: Get React Native Arsenal
              run: |
                  git clone https://gitlab.com/nepware-internals/react-native-arsenal.git src/vendor/react-native-arsenal

            - name: Gradle Wrapper Validation
              uses: gradle/wrapper-validation-action@v1

            - name: ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                create-symlink: true

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '18'
                  cache: 'gradle'

            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.0'
                bundler-cache: true
                working-directory: 'android'

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
                  cache-dependency-path: '**/yarn.lock'

            - name: Install Dependencies
              run: |
                  yarn install --non-interactive
                  echo MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN >> ./android/gradle.properties

            - name: Run Fastlane
              uses: maierj/fastlane-action@v3.0.0
              with:
                  lane: ${{ github.ref_type == 'tag' && 'beta' || 'build' }}
                  subdirectory: 'android'
              env:
                  FASTLANE_HIDE_CHANGELOG: true

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: apk
                  path: |
                    android/app/build/outputs/apk/release
                  retention-days: 14
